set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

if(DEFINED ENV{OPENIPC_ARM_GCC_PREFIX})
    set(OPENIPC_ARM_GCC_PREFIX "$ENV{OPENIPC_ARM_GCC_PREFIX}")
elseif(DEFINED ENV{OPENIPC_ARM_TOOLCHAIN_PREFIX})
    set(OPENIPC_ARM_GCC_PREFIX "$ENV{OPENIPC_ARM_TOOLCHAIN_PREFIX}")
elseif(EXISTS "/opt/homebrew/bin/armv7-unknown-linux-gnueabihf-gcc")
    set(OPENIPC_ARM_GCC_PREFIX "/opt/homebrew/bin/armv7-unknown-linux-gnueabihf-")
elseif(EXISTS "/usr/local/bin/armv7-unknown-linux-gnueabihf-gcc")
    set(OPENIPC_ARM_GCC_PREFIX "/usr/local/bin/armv7-unknown-linux-gnueabihf-")
elseif(EXISTS "/opt/homebrew/bin/arm-linux-gnueabihf-gcc")
    set(OPENIPC_ARM_GCC_PREFIX "/opt/homebrew/bin/arm-linux-gnueabihf-")
elseif(EXISTS "/usr/local/bin/arm-linux-gnueabihf-gcc")
    set(OPENIPC_ARM_GCC_PREFIX "/usr/local/bin/arm-linux-gnueabihf-")
elseif(EXISTS "/opt/homebrew/bin/arm-unknown-linux-gnueabihf-gcc")
    set(OPENIPC_ARM_GCC_PREFIX "/opt/homebrew/bin/arm-unknown-linux-gnueabihf-")
elseif(EXISTS "/usr/local/bin/arm-unknown-linux-gnueabihf-gcc")
    set(OPENIPC_ARM_GCC_PREFIX "/usr/local/bin/arm-unknown-linux-gnueabihf-")
else()
    set(OPENIPC_ARM_GCC_PREFIX "armv7-unknown-linux-gnueabihf-")
endif()

set(CMAKE_C_COMPILER "${OPENIPC_ARM_GCC_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${OPENIPC_ARM_GCC_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${OPENIPC_ARM_GCC_PREFIX}gcc")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
